---
sudo: false

language: go
go:
    - '1.10'
    - '1.11'

install:
    # this is bad but it's ci so i don't really care
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
    - make test && make

notifications:
    email: false
